# Generated by Django 4.2.27 manually

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, help_text='Unique key for the feature flag (e.g., FEATURE_CSR)', max_length=64, unique=True)),
                ('enabled', models.BooleanField(default=False, help_text='Whether this feature is globally enabled')),
                ('description', models.TextField(blank=True, help_text='Description of what this flag controls')),
            ],
            options={
                'verbose_name': 'Feature Flag',
                'verbose_name_plural': 'Feature Flags',
                'db_table': 'feature_flags',
                'ordering': ['key'],
            },
        ),
    ]
