# Generated by Django 4.2.27 on 2026-01-03 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("services", "0002_add_bilingual_fields"),
        ("workers", "0005_add_availability_and_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contractors", "0004_add_site_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact_phone",
                    models.CharField(
                        db_index=True,
                        help_text="Contact phone number for emergency",
                        max_length=20,
                    ),
                ),
                (
                    "location_lat",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Emergency location latitude",
                        max_digits=9,
                    ),
                ),
                (
                    "location_lng",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Emergency location longitude",
                        max_digits=9,
                    ),
                ),
                ("address_text", models.TextField(help_text="Human-readable address")),
                (
                    "service_description",
                    models.TextField(
                        blank=True,
                        help_text="Additional service details or custom description",
                    ),
                ),
                (
                    "urgency_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        db_index=True,
                        default="high",
                        help_text="Urgency level of request",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("dispatched", "Dispatched"),
                            ("accepted", "Accepted"),
                            ("on_the_way", "On The Way"),
                            ("resolved", "Resolved"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="open",
                        help_text="Current status of emergency",
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Auto-assign audit, escalation notes, dispatch info",
                    ),
                ),
                (
                    "assigned_contractor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Contractor for escalated emergencies",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="escalated_emergencies",
                        to="contractors.contractorprofile",
                    ),
                ),
                (
                    "assigned_worker",
                    models.ForeignKey(
                        blank=True,
                        help_text="Worker who accepted the emergency",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_emergencies",
                        to="workers.workerprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created request (can be null for anonymous)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emergency_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service_required",
                    models.ForeignKey(
                        blank=True,
                        help_text="Service type needed",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emergencies",
                        to="services.service",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        help_text="Related construction site (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="emergencies",
                        to="contractors.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emergency Request",
                "verbose_name_plural": "Emergency Requests",
                "db_table": "emergency_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyDispatchLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attempt_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When notification was sent",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("notified", "Notified"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("timeout", "Timeout"),
                        ],
                        db_index=True,
                        default="notified",
                        help_text="Dispatch attempt status",
                        max_length=20,
                    ),
                ),
                (
                    "response_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="When worker responded (accepted/declined)",
                        null=True,
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Raw notification response data (distance, FCM response, etc.)",
                    ),
                ),
                (
                    "emergency",
                    models.ForeignKey(
                        help_text="Emergency request being dispatched",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dispatch_logs",
                        to="emergency.emergencyrequest",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        help_text="Worker who was notified",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_notifications",
                        to="workers.workerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emergency Dispatch Log",
                "verbose_name_plural": "Emergency Dispatch Logs",
                "db_table": "emergency_dispatch_logs",
                "ordering": ["-attempt_time"],
            },
        ),
        migrations.AddIndex(
            model_name="emergencyrequest",
            index=models.Index(
                fields=["status", "urgency_level"], name="emergency_status_urgency_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencyrequest",
            index=models.Index(
                fields=["contact_phone", "created_at"],
                name="emergency_phone_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emergencyrequest",
            index=models.Index(
                fields=["location_lat", "location_lng"], name="emergency_location_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencyrequest",
            index=models.Index(
                fields=["created_at", "status"], name="emergency_created_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencydispatchlog",
            index=models.Index(
                fields=["emergency", "status"], name="dispatch_emergency_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencydispatchlog",
            index=models.Index(
                fields=["worker", "attempt_time"], name="dispatch_worker_time_idx"
            ),
        ),
    ]
