# Generated by Django 4.2.27 manually

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_add_job_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='instruction_audio_url',
            field=models.URLField(blank=True, help_text='Audio URL for job instructions (for Listen button)', max_length=500, null=True),
        ),
    ]
