# Generated by Django 4.2.27 manually

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('jobs', '0003_add_instruction_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='photos',
            field=models.ManyToManyField(blank=True, help_text='Photos attached to the job', related_name='job_photos', to='media.mediaobject'),
        ),
    ]
