# Generated by Django 4.2.27 on 2026-01-02 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_initial"),
        ("jobs", "0004_add_photos"),
    ]

    operations = []
