# Generated by Django 4.2.27 manually

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
        ('jobs', '0005_merge_0002_initial_0004_add_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contractor',
            field=models.ForeignKey(
                blank=True,
                help_text='Contractor responsible for this job',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='jobs',
                to='contractors.contractorprofile'
            ),
        ),
    ]
