# Generated by Django 4.2.27 manually

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(default='', help_text='English title for service', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='title_hi',
            field=models.CharField(blank=True, help_text='Hindi title for service', max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, help_text='Category grouping (e.g., construction, home_services)', max_length=50),
        ),
    ]
