# Generated by Django 4.2.27 on 2026-01-01 15:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=300)),
                (
                    "image_s3_key",
                    models.CharField(
                        help_text="S3/MinIO key for banner image", max_length=500
                    ),
                ),
                (
                    "action",
                    models.JSONField(
                        default=dict,
                        help_text='Action on tap: {"type": "url"|"route", "value": "https://..." or "/route"}',
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Lower values appear first"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "primary_color",
                    models.CharField(
                        default="#2563EB", help_text="Hex color code", max_length=7
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#F59E0B", help_text="Hex color code", max_length=7
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        default="#F9FAFB", help_text="Hex color code", max_length=7
                    ),
                ),
                (
                    "logo_s3_key",
                    models.CharField(
                        blank=True,
                        help_text="S3/MinIO key for logo image",
                        max_length=500,
                    ),
                ),
                (
                    "fonts",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Array of font objects: [{"family": "Inter", "s3_key": "fonts/inter.woff"}]',
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional theme metadata"
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=False, help_text="Only one theme can be active"
                    ),
                ),
            ],
            options={
                "ordering": ["-active", "-created_at"],
            },
        ),
    ]
