# Generated by Django 4.2.27 manually

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='hero_image_s3_key',
            field=models.CharField(blank=True, help_text='S3/MinIO key for hero/banner image', max_length=500),
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.UUIDField(default='uuid.uuid4', editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, help_text="Translation key (e.g., 'apply_now')", max_length=255)),
                ('lang', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi')], help_text='Language code', max_length=2)),
                ('value', models.TextField(help_text='Translated text')),
            ],
            options={
                'ordering': ['key', 'lang'],
                'unique_together': {('key', 'lang')},
            },
        ),
        migrations.AddIndex(
            model_name='translation',
            index=models.Index(fields=['key', 'lang'], name='core_transl_key_0d2e9c_idx'),
        ),
    ]
