# Generated by Django 4.2.27 on 2026-01-12 15:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_merge_20260103_0112'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='translation',
            new_name='core_transl_key_9f2127_idx',
            old_name='core_transl_key_0d2e9c_idx',
        ),
        migrations.AlterField(
            model_name='translation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
