# Generated by Django 4.2.27 manually

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhaar_last4_encrypted',
            field=models.BinaryField(blank=True, help_text='Encrypted last 4 digits of Aadhaar (NEVER store full Aadhaar)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ekyc_status',
            field=models.CharField(
                choices=[('none', 'None'), ('ocr_scanned', 'OCR Scanned'), ('verified', 'Verified')],
                default='none',
                help_text='eKYC verification status',
                max_length=16
            ),
        ),
    ]
