# Generated by Django 4.2.27 on 2026-01-02 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_ekyc_fields"),
        ("users", "0002_otplog_user_is_phone_verified_user_profile_picture"),
    ]

    operations = []
