# Generated by Django 4.2.27 on 2026-01-12 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_otpverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
