# Generated by Django 4.2.27 on 2026-01-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='min_charge',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum charge for service', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Worker's rate/price", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='price_currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='price_type',
            field=models.CharField(choices=[('per_hour', 'Per Hour'), ('per_day', 'Per Day'), ('per_job', 'Per Job')], default='per_day', help_text='Pricing model (per hour/day/job)', max_length=16),
        ),
    ]
