# Generated by Django 4.2.27 manually

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_add_pricing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='intro_audio_url',
            field=models.URLField(blank=True, help_text='Audio URL for worker introduction (for Listen button)', max_length=500, null=True),
        ),
    ]
