# Generated by Django 4.2.27 manually

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('workers', '0003_add_intro_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='gallery',
            field=models.ManyToManyField(blank=True, help_text='Image gallery for worker profile', related_name='worker_galleries', to='media.mediaobject'),
        ),
    ]
