# Generated by Django 4.2.27 on 2026-01-03 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workers", "0004_add_gallery"),
    ]

    operations = [
        migrations.AddField(
            model_name="workerprofile",
            name="availability_updated_at",
            field=models.DateTimeField(
                blank=True, help_text="Last time availability was toggled", null=True
            ),
        ),
        migrations.AddField(
            model_name="workerprofile",
            name="is_available",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Worker is online and available for bookings",
            ),
        ),
        migrations.AddIndex(
            model_name="workerprofile",
            index=models.Index(
                fields=["is_available", "latitude", "longitude"],
                name="worker_nearby_idx",
            ),
        ),
    ]
