# Generated by Django 4.2.27 manually

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_add_theme_hero_and_translations'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaObject',
            fields=[
                ('id', models.UUIDField(default='uuid.uuid4', editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(help_text='MinIO object key (path in storage)', max_length=255, unique=True)),
                ('url', models.URLField(help_text='Public URL to access the media', max_length=500)),
                ('file_type', models.CharField(choices=[('image/jpeg', 'JPEG Image'), ('image/png', 'PNG Image'), ('image/webp', 'WebP Image'), ('audio/mpeg', 'MP3 Audio'), ('audio/wav', 'WAV Audio')], help_text='MIME type of the file', max_length=32)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Media Object',
                'verbose_name_plural': 'Media Objects',
                'db_table': 'media_objects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mediaobject',
            index=models.Index(fields=['uploaded_by', '-created_at'], name='media_objec_uploade_9c3e4a_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaobject',
            index=models.Index(fields=['file_type'], name='media_objec_file_ty_5e2b0f_idx'),
        ),
    ]
