# Generated by Django 4.2.27 on 2026-01-12 15:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mediaobject',
            new_name='media_objec_uploade_e4c109_idx',
            old_name='media_objec_uploade_9c3e4a_idx',
        ),
        migrations.RenameIndex(
            model_name='mediaobject',
            new_name='media_objec_file_ty_d6ad77_idx',
            old_name='media_objec_file_ty_5e2b0f_idx',
        ),
        migrations.AlterField(
            model_name='mediaobject',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
