# Generated by Django 4.2.27 on 2026-01-01 15:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContractorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("license_number", models.CharField(blank=True, max_length=100)),
                ("gst_number", models.CharField(blank=True, max_length=15)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("postal_code", models.CharField(blank=True, max_length=10)),
                ("website", models.URLField(blank=True)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
                ),
                ("total_projects", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Contractor Profile",
                "verbose_name_plural": "Contractor Profiles",
                "db_table": "contractor_profiles",
            },
        ),
    ]
