# Generated by Django 4.2.27 manually

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this contractor profile is active'),
        ),
    ]
