# Generated by Django 4.2.27 on 2026-01-03 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workers", "0005_add_availability_and_location"),
        ("contractors", "0003_merge_0002_contractorprofile_is_active_0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(help_text="Site name/identifier", max_length=255),
                ),
                ("address", models.TextField(help_text="Full site address")),
                (
                    "lat",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Latitude for site location",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Longitude for site location",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Site contact phone number",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether this site is currently active",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, help_text="Project start date", null=True
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Expected/actual project end date",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional site metadata (JSON)",
                    ),
                ),
                (
                    "contractor",
                    models.ForeignKey(
                        help_text="Contractor who owns this site",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to="contractors.contractorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Construction Site",
                "verbose_name_plural": "Construction Sites",
                "db_table": "contractor_sites",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attendance_date",
                    models.DateField(db_index=True, help_text="Date of attendance"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("half_day", "Half Day"),
                            ("on_leave", "On Leave"),
                        ],
                        default="absent",
                        help_text="Attendance status",
                        max_length=20,
                    ),
                ),
                (
                    "checkin_time",
                    models.DateTimeField(
                        blank=True, help_text="Time when worker checked in", null=True
                    ),
                ),
                (
                    "checkout_time",
                    models.DateTimeField(
                        blank=True, help_text="Time when worker checked out", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about attendance"
                    ),
                ),
                (
                    "marked_by",
                    models.ForeignKey(
                        help_text="User/device that marked attendance",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_marked",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        help_text="Site where attendance is recorded",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to="contractors.site",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        help_text="Worker for whom attendance is recorded",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_attendance",
                        to="workers.workerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Attendance",
                "verbose_name_plural": "Site Attendance Records",
                "db_table": "site_attendance",
                "ordering": ["-attendance_date", "site"],
                "indexes": [
                    models.Index(
                        fields=["site", "attendance_date"],
                        name="attendance_site_date_idx",
                    ),
                    models.Index(
                        fields=["worker", "attendance_date"],
                        name="attendance_worker_date_idx",
                    ),
                    models.Index(
                        fields=["attendance_date", "status"],
                        name="attendance_date_status_idx",
                    ),
                ],
                "unique_together": {("site", "worker", "attendance_date")},
            },
        ),
        migrations.CreateModel(
            name="SiteAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When worker was assigned"
                    ),
                ),
                (
                    "role_on_site",
                    models.CharField(
                        blank=True,
                        help_text="Worker's role on this site (e.g., Mason, Plumber)",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether assignment is currently active",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        help_text="User who made the assignment",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        help_text="Site where worker is assigned",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="contractors.site",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        help_text="Worker assigned to site",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="site_assignments",
                        to="workers.workerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Assignment",
                "verbose_name_plural": "Site Assignments",
                "db_table": "site_assignments",
                "ordering": ["-assigned_at"],
                "indexes": [
                    models.Index(
                        fields=["site", "is_active"], name="assignment_site_active_idx"
                    ),
                    models.Index(
                        fields=["worker", "is_active"],
                        name="assignment_worker_active_idx",
                    ),
                ],
                "unique_together": {("site", "worker")},
            },
        ),
        migrations.AddIndex(
            model_name="site",
            index=models.Index(
                fields=["contractor", "is_active"], name="site_contractor_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="site",
            index=models.Index(
                fields=["is_active", "created_at"], name="site_active_created_idx"
            ),
        ),
    ]
