# Generated by Django 4.2.27 on 2026-01-01 15:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttendanceKiosk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("device_uuid", models.CharField(max_length=100, unique=True)),
                ("location_name", models.CharField(max_length=200)),
                ("address", models.TextField(blank=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Attendance Kiosk",
                "verbose_name_plural": "Attendance Kiosks",
                "db_table": "attendance_kiosks",
            },
        ),
        migrations.CreateModel(
            name="AttendanceLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("check_in", models.DateTimeField(auto_now_add=True)),
                ("check_out", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "kiosk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logs",
                        to="attendance.attendancekiosk",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Log",
                "verbose_name_plural": "Attendance Logs",
                "db_table": "attendance_logs",
                "ordering": ["-check_in"],
            },
        ),
    ]
