# Generated by Django 4.2.27 manually

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancekiosk',
            name='contractor',
            field=models.ForeignKey(
                blank=True,
                help_text='Contractor who owns/manages this site',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='kiosks',
                to='contractors.contractorprofile'
            ),
        ),
    ]
