# Generated by Django 4.2.27 manually

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0002_attendancekiosk_contractor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default='uuid.uuid4', editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(
                    choices=[('stub', 'Stub'), ('biometric', 'Biometric')],
                    default='stub',
                    help_text='Method used to mark attendance',
                    max_length=20
                )),
                ('device_id', models.CharField(
                    blank=True,
                    help_text='Device identifier (e.g., KIOSK_001)',
                    max_length=64,
                    null=True
                )),
                ('timestamp', models.DateTimeField(
                    auto_now_add=True,
                    help_text='Exact time when attendance was marked'
                )),
                ('date', models.DateField(
                    db_index=True,
                    help_text='Date of attendance (derived from timestamp)'
                )),
                ('kiosk', models.ForeignKey(
                    blank=True,
                    help_text='Kiosk/site where attendance was marked',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='attendances',
                    to='attendance.attendancekiosk'
                )),
                ('worker', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='attendances',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'db_table': 'attendances',
                'ordering': ['-date', '-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['worker', 'date'], name='attendances_worker_d9c8a2_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['kiosk', 'date'], name='attendances_kiosk_i_3f7e91_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='attendances_date_8a4b5c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('worker', 'date')},
        ),
    ]
