# Generated by Django 4.2.27 on 2026-01-03 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_initial"),
        ("attendance", "0003_attendance"),
    ]

    operations = []
