# Generated by Django 4.2.27 on 2026-01-12 15:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_merge_0002_initial_0003_attendance'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendance',
            new_name='attendances_worker__583538_idx',
            old_name='attendances_worker_d9c8a2_idx',
        ),
        migrations.RenameIndex(
            model_name='attendance',
            new_name='attendances_kiosk_i_6bd377_idx',
            old_name='attendances_kiosk_i_3f7e91_idx',
        ),
        migrations.RenameIndex(
            model_name='attendance',
            new_name='attendances_date_234e8d_idx',
            old_name='attendances_date_8a4b5c_idx',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
