# Generated by Django 4.2.27 manually

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency('users.User'),
        ('workers', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=512)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('preferred_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('on_the_way', 'On The Way'), ('arrived', 'Arrived'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('payment_pending', 'Payment Pending')], db_index=True, default='requested', max_length=32)),
                ('eta_minutes', models.IntegerField(blank=True, help_text='Estimated arrival time in minutes', null=True)),
                ('tracking_url', models.URLField(blank=True, help_text='Live location tracking URL', null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.service')),
                ('user', models.ForeignKey(help_text='Employer who booked the service', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.User')),
                ('worker', models.ForeignKey(blank=True, help_text='Assigned worker', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='workers.workerprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='bookings_bo_status_c0d12e_idx')],
            },
        ),
    ]
