# Generated by Django 4.2.27 on 2026-01-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(
                choices=[('cash', 'Cash'), ('online', 'Online'), ('none', 'None')],
                default='cash',
                help_text='Payment method for this booking',
                max_length=8
            ),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(
                choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('n/a', 'Not Applicable')],
                default='n/a',
                help_text='Payment status (n/a for cash)',
                max_length=16
            ),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_note',
            field=models.TextField(
                blank=True,
                help_text='Notes about payment (e.g., auto-fallback)',
                null=True
            ),
        ),
    ]
