# Generated by Django 4.2.27 on 2026-01-03 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_add_payment_method_status"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="booking",
            new_name="bookings_bo_status_72dd85_idx",
            old_name="bookings_bo_status_c0d12e_idx",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="payment_note",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="payment_status",
        ),
    ]
