# Generated by Django 4.2.27 on 2026-01-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_merge_migrations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='last_location',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='last_location_time',
        ),
    ]
