# Generated by Django 4.2.27 manually

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(
                    db_index=True,
                    help_text="Event name (e.g., 'job_apply_clicked', 'screen_viewed')",
                    max_length=100
                )),
                ('payload', models.JSONField(
                    blank=True,
                    default=dict,
                    help_text='Event-specific data as JSON'
                )),
                ('source', models.CharField(
                    choices=[
                        ('mobile', 'Mobile App'),
                        ('web', 'Web App'),
                        ('admin', 'Admin Panel')
                    ],
                    db_index=True,
                    default='mobile',
                    help_text='Source platform of the event',
                    max_length=20
                )),
                ('user', models.ForeignKey(
                    blank=True,
                    help_text='User who triggered the event (optional)',
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='analytics_events',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'analytics_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['name', 'created_at'], name='analytics_e_name_4a8b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', 'created_at'], name='analytics_e_user_id_7d9e3f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['source', 'created_at'], name='analytics_e_source_5f2a1d_idx'),
        ),
    ]
