# Generated by Django 4.2.27 on 2026-01-11 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAggregateDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='Aggregation date')),
                ('event_type', models.CharField(db_index=True, help_text='Event type', max_length=50)),
                ('source', models.CharField(blank=True, help_text='Source platform (optional)', max_length=20)),
                ('count', models.IntegerField(default=0, help_text='Number of events')),
                ('unique_users', models.IntegerField(default=0, help_text='Number of unique user IDs')),
                ('unique_anonymous', models.IntegerField(default=0, help_text='Number of unique anonymous IDs')),
                ('meta', models.JSONField(blank=True, default=dict, help_text='Additional aggregate metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Event Aggregate',
                'verbose_name_plural': 'Daily Event Aggregates',
                'db_table': 'analytics_event_aggregates_daily',
                'ordering': ['-date', 'event_type'],
                'indexes': [models.Index(fields=['date', 'event_type'], name='agg_date_type_idx')],
                'unique_together': {('date', 'event_type', 'source')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anonymous_id', models.CharField(blank=True, db_index=True, help_text='Client-generated anonymous ID for tracking', max_length=255, null=True)),
                ('event_type', models.CharField(db_index=True, help_text='Type of event', max_length=50)),
                ('source', models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('ios', 'iOS'), ('kiosk', 'Kiosk'), ('admin', 'Admin')], db_index=True, default='web', help_text='Event source platform', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Event metadata (max 2KB)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Client user agent', max_length=500, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User if logged in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'db_table': 'analytics_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='analytics_created_idx'), models.Index(fields=['event_type', 'created_at'], name='analytics_type_created_idx'), models.Index(fields=['user', 'created_at'], name='analytics_user_created_idx'), models.Index(fields=['-created_at', 'event_type'], name='analytics_recent_type_idx')],
            },
        ),
    ]
