# Generated by Django 4.2.27 manually

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Banner title (internal use)', max_length=255)),
                ('image_url', models.URLField(help_text='Public URL to banner image (MinIO or CDN)', max_length=500)),
                ('link', models.URLField(blank=True, help_text='Optional destination URL when banner is clicked', max_length=500, null=True)),
                ('slot', models.CharField(
                    choices=[
                        ('home_top', 'Home Top'),
                        ('home_mid', 'Home Mid'),
                        ('home_bottom', 'Home Bottom'),
                        ('worker_top', 'Worker Top'),
                        ('job_top', 'Job Top')
                    ],
                    db_index=True,
                    default='home_top',
                    help_text='Banner placement slot',
                    max_length=50
                )),
                ('priority', models.IntegerField(db_index=True, default=0, help_text='Higher priority banners shown first')),
                ('active', models.BooleanField(db_index=True, default=True, help_text='Whether this banner is currently active')),
                ('starts_at', models.DateTimeField(blank=True, help_text='Banner becomes visible at this time (optional)', null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Banner becomes hidden after this time (optional)', null=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'db_table': 'cms_banners',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['slot', 'active', 'priority'], name='cms_banners_slot_ac_4f2a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='banner',
            index=models.Index(fields=['active', 'starts_at', 'ends_at'], name='cms_banners_active_5c7d9e_idx'),
        ),
    ]
