# Generated by Django 4.2.27 on 2026-01-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='banner',
            new_name='cms_banners_slot_d794c6_idx',
            old_name='cms_banners_slot_ac_4f2a3b_idx',
        ),
        migrations.RenameIndex(
            model_name='banner',
            new_name='cms_banners_active_2db3fa_idx',
            old_name='cms_banners_active_5c7d9e_idx',
        ),
    ]
