# Generated by Django 4.2.27 manually

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='URL-safe identifier for the help page', max_length=100, unique=True)),
                ('title', models.CharField(help_text='Title of the help page', max_length=255)),
                ('content_html', models.TextField(help_text='HTML content of the help page')),
                ('lang', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi')], default='en', help_text='Language of the content', max_length=5)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this help page is visible to users')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
            ],
            options={
                'verbose_name': 'Help Page',
                'verbose_name_plural': 'Help Pages',
                'db_table': 'help_pages',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(help_text='The question', max_length=255)),
                ('answer', models.TextField(help_text='The answer to the question')),
                ('lang', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi')], default='en', help_text='Language of the content', max_length=5)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this FAQ is visible to users')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'db_table': 'faqs',
                'ordering': ['order', 'question'],
            },
        ),
        migrations.AddIndex(
            model_name='helppage',
            index=models.Index(fields=['lang', 'is_active'], name='help_pages_lang_2a5e0f_idx'),
        ),
        migrations.AddIndex(
            model_name='helppage',
            index=models.Index(fields=['order'], name='help_pages_order_8c4b1e_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['lang', 'is_active'], name='faqs_lang_5d6f8a_idx'),
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['order'], name='faqs_order_7a9c2d_idx'),
        ),
    ]
