# Generated by Django 4.2.27 on 2026-01-12 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='faq',
            new_name='faqs_lang_319e6e_idx',
            old_name='faqs_lang_5d6f8a_idx',
        ),
        migrations.RenameIndex(
            model_name='faq',
            new_name='faqs_order_d2a62f_idx',
            old_name='faqs_order_7a9c2d_idx',
        ),
        migrations.RenameIndex(
            model_name='helppage',
            new_name='help_pages_lang_cc8428_idx',
            old_name='help_pages_lang_2a5e0f_idx',
        ),
        migrations.RenameIndex(
            model_name='helppage',
            new_name='help_pages_order_87f5b5_idx',
            old_name='help_pages_order_8c4b1e_idx',
        ),
    ]
