# Generated by Django 4.2.27 manually

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('job_assigned', 'Job Assigned'),
                    ('job_completed', 'Job Completed'),
                    ('job_application', 'Job Application'),
                    ('application_accepted', 'Application Accepted'),
                    ('application_declined', 'Application Declined'),
                    ('payment_received', 'Payment Received'),
                    ('message', 'Message'),
                    ('system', 'System')
                ],
                max_length=50
            ),
        ),
    ]
