# Generated by Django 4.2.27 on 2026-01-03 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_update_notifications_add_timeline"),
        ("jobs", "0006_job_contractor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0003_merge_0002_initial_0002_update_notification_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimelineEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("booking_requested", "Booking Requested"),
                            ("booking_confirmed", "Booking Confirmed"),
                            ("booking_on_the_way", "On The Way"),
                            ("booking_arrived", "Arrived"),
                            ("booking_completed", "Completed"),
                            ("booking_cancelled", "Cancelled"),
                            ("job_applied", "Job Applied"),
                            ("job_accepted", "Job Accepted"),
                            ("worker_assigned", "Worker Assigned"),
                            ("attendance_marked", "Attendance Marked"),
                            ("payment_captured", "Payment Captured"),
                            ("payment_failed", "Payment Failed"),
                            ("custom", "Custom"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "actor_display",
                    models.CharField(
                        help_text="Human-readable actor name (e.g., 'John Doe', 'System')",
                        max_length=255,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Event-specific data (status, worker_id, etc.)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timeline Event",
                "verbose_name_plural": "Timeline Events",
                "db_table": "timeline_events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.RemoveField(
            model_name="notification",
            name="notification_type",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="sent_at",
        ),
        migrations.AddField(
            model_name="notification",
            name="channel",
            field=models.CharField(
                choices=[
                    ("push", "Push Notification"),
                    ("in_app", "In-App"),
                    ("email", "Email"),
                ],
                default="in_app",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("booking_status", "Booking Status"),
                    ("job_application", "Job Application"),
                    ("assignment", "Assignment"),
                    ("attendance", "Attendance"),
                    ("system", "System"),
                    ("promo", "Promo"),
                ],
                db_index=True,
                default="system",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="data",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional payload (booking_id, type, etc.)",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Recipient (null for broadcast notifications)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read", "-created_at"],
                name="notificatio_user_id_c4e471_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["type", "-created_at"], name="notificatio_type_d2e2f1_idx"
            ),
        ),
        migrations.AddField(
            model_name="timelineevent",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                help_text="Related booking",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeline_events",
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="timelineevent",
            name="job",
            field=models.ForeignKey(
                blank=True,
                help_text="Related job",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeline_events",
                to="jobs.job",
            ),
        ),
        migrations.AddField(
            model_name="timelineevent",
            name="related_user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who triggered this event",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="timelineevent",
            index=models.Index(
                fields=["booking", "-created_at"], name="timeline_ev_booking_1ef4bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timelineevent",
            index=models.Index(
                fields=["job", "-created_at"], name="timeline_ev_job_id_650b07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timelineevent",
            index=models.Index(
                fields=["event_type", "-created_at"],
                name="timeline_ev_event_t_603a4d_idx",
            ),
        ),
    ]
