# Generated by Django 4.2.27 on 2026-01-03 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0004_update_notifications_add_timeline"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("android", "Android"),
                            ("ios", "iOS"),
                            ("web", "Web"),
                        ],
                        help_text="Device platform",
                        max_length=10,
                    ),
                ),
                (
                    "registration_token",
                    models.CharField(
                        db_index=True,
                        help_text="FCM registration token",
                        max_length=500,
                        unique=True,
                    ),
                ),
                (
                    "last_seen",
                    models.DateTimeField(
                        auto_now=True, help_text="Last time device checked in"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Whether device is active",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Device info: model, OS version, app version",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User associated with device (null if unregistered)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
                "db_table": "notification_devices",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="OutgoingPush",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "payload",
                    models.JSONField(default=dict, help_text="FCM payload sent"),
                ),
                (
                    "provider_response",
                    models.JSONField(
                        blank=True, default=dict, help_text="FCM response data"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("delayed", "Delayed"),
                        ],
                        db_index=True,
                        default="queued",
                        help_text="Delivery status",
                        max_length=10,
                    ),
                ),
                (
                    "attempts",
                    models.IntegerField(
                        default=0, help_text="Number of delivery attempts"
                    ),
                ),
                (
                    "last_attempt_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last delivery attempt timestamp",
                        null=True,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target device",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_pushes",
                        to="notifications.device",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source notification",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="outgoing_pushes",
                        to="notifications.notification",
                    ),
                ),
            ],
            options={
                "verbose_name": "Outgoing Push",
                "verbose_name_plural": "Outgoing Pushes",
                "db_table": "notification_outgoing_pushes",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="push_status_created_idx"
                    ),
                    models.Index(
                        fields=["device", "status"], name="push_device_status_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="device",
            index=models.Index(
                fields=["user", "is_active"], name="device_user_active_idx"
            ),
        ),
    ]
